export const queryParams = {
  search: 'search',
  copyAddress: 'copy-address',
  receive: 'receive',
  btcDeposit: 'btcDeposit',
  faucetError: 'faucet-error',
  faucetSuccess: 'faucet-success',
  txDeclined: 'tx-declined',
  walletAvatarChanged: 'wallet-avatar-changed',
  chadEligibility: 'chad-eligibility',
  alphaBookmarks: 'alpha-bookmarks',
  alphaTags: 'alpha-tags',
  alphaTab: 'tab',
  alphaDateStatus: 'status',
}
