import { Cw20Denoms } from './cw20-denoms';

export type SupportedDenoms = 'uatom' | 'uosmo' | 'uion' | 'uscrt' | 'ujuno' | 'ujunox' | 'ustars' | 'uusdc' | 'usdc';

export type NativeDenom = {
  coinDenom: string;
  coinMinimalDenom: string;
  coinDecimals: number;
  icon: string;
  chain: string;
  coinGeckoId: string;
  name?: string;
  description?: string;
  ibcDenom?: string;
};

export type Denoms = Record<SupportedDenoms, NativeDenom>;

export const denoms = {
  wei: {
    coinDenom: 'ETH',
    coinMinimalDenom: 'wei',
    coinDecimals: 18,
    coinGeckoId: 'ethereum',
    icon: 'https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/centauri/eth.png',
    chain: 'ethereum',
  },
  uinit: {
    coinDenom: 'INIT',
    coinMinimalDenom: 'uinit',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/initia.svg',
    chain: 'initia',
    coinGeckoId: '',
  },
  usaga: {
    coinDenom: 'SAGA',
    coinMinimalDenom: 'usaga',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/saga.svg',
    chain: 'saga',
    coinGeckoId: 'saga-2',
  },
  udym: {
    coinDenom: 'DYM',
    coinDecimals: 18,
    coinMinimalDenom: 'udym',
    icon: 'https://assets.leapwallet.io/dymension-logo.svg',
    chain: 'dymension',
    coinGeckoId: '',
  },
  adym: {
    coinDenom: 'DYM',
    coinDecimals: 18,
    coinMinimalDenom: 'adym',
    icon: 'https://assets.leapwallet.io/dymension-logo.svg',
    chain: 'dymension',
    coinGeckoId: '',
  },
  rune: {
    coinDenom: 'RUNE',
    coinDecimals: 8,
    coinMinimalDenom: 'rune',
    icon: 'https://assets.leapwallet.io/thorchain.svg',
    chain: 'thorchain',
    coinGeckoId: 'thorchain',
  },
  upryzm: {
    coinDenom: 'PRYZM',
    coinDecimals: 6,
    coinMinimalDenom: 'upryzm',
    icon: 'https://assets.leapwallet.io/pryzm.svg',
    chain: 'pryzmtestnet',
    coinGeckoId: '',
  },
  adydx: {
    coinDenom: 'DYDX',
    coinDecimals: 18,
    coinMinimalDenom: 'adydx',
    icon: 'https://assets.leapwallet.io/dydx.png',
    chain: 'dydx',
    coinGeckoId: 'dydx',
  },
  axpla: {
    coinDenom: 'XPLA',
    coinDecimals: 18,
    coinMinimalDenom: 'axpla',
    icon: 'https://assets.leapwallet.io/xpla.svg',
    chain: 'xpla',
    coinGeckoId: 'xpla',
  },
  nhash: {
    coinDenom: 'HASH',
    coinMinimalDenom: 'nhash',
    coinDecimals: 9,
    coinGeckoId: '',
    icon: 'https://assets.leapwallet.io/provenance.svg',
    chain: 'provenance',
  },
  uaura: {
    coinDenom: 'AURA',
    coinDecimals: 6,
    coinMinimalDenom: 'uaura',
    icon: 'https://assets.leapwallet.io/aura.svg',
    chain: 'aura',
    coinGeckoId: 'aura-network',
  },
  uxki: {
    coinDenom: 'XKI',
    coinMinimalDenom: 'uxki',
    coinDecimals: 6,
    coinGeckoId: 'ki',
    icon: 'https://assets.leapwallet.io/xki.svg',
    chain: 'kichain',
  },
  udvpn: {
    coinDenom: 'DVPN',
    coinMinimalDenom: 'udvpn',
    coinDecimals: 6,
    coinGeckoId: 'sentinel',
    icon: 'https://assets.leapwallet.io/sentinel.svg',
    chain: 'sentinel',
  },
  uband: {
    coinDenom: 'BAND',
    coinDecimals: 6,
    coinMinimalDenom: 'uband',
    icon: 'https://assets.leapwallet.io/band.svg',
    chain: 'bandchain',
    coinGeckoId: 'band-protocol',
  },
  usge: {
    coinDenom: 'SGE',
    coinDecimals: 6,
    coinMinimalDenom: 'usge',
    icon: 'https://assets.leapwallet.io/sge.svg',
    chain: 'sge',
    coinGeckoId: '',
  },
  utia: {
    coinDenom: 'TIA',
    coinDecimals: 6,
    coinMinimalDenom: 'utia',
    icon: 'https://assets.leapwallet.io/filled-celestia.svg',
    chain: 'celestia',
    coinGeckoId: '',
  },
  dv4tnt: {
    coinDenom: 'DV4TNT',
    coinDecimals: 6,
    coinMinimalDenom: 'dv4tnt',
    icon: 'https://assets.leapwallet.io/dydx.png',
    chain: 'dydx',
    coinGeckoId: '',
  },
  umpwr: {
    coinDenom: 'MPWR',
    coinMinimalDenom: 'umpwr',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/empower-testnet.png',
    chain: 'empowerchain',
    coinGeckoId: '',
  },
  unibi: {
    coinDenom: 'NIBI',
    coinMinimalDenom: 'unibi',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/nibiru.png',
    chain: 'nibiru',
    coinGeckoId: 'nibi',
  },
  cacao: {
    coinDenom: 'CACAO',
    coinMinimalDenom: 'cacao',
    coinDecimals: 10,
    icon: 'https://assets.leapwallet.io/cacao.png',
    chain: 'juno',
    coinGeckoId: 'cacao',
  },
  maya: {
    coinDenom: 'MAYA',
    coinMinimalDenom: 'maya',
    coinDecimals: 4,
    icon: 'https://assets.leapwallet.io/maya-token.png',
    chain: 'mayachain',
    coinGeckoId: '',
  },
  ustake: {
    coinDenom: 'STAKE',
    coinMinimalDenom: 'ustake',
    coinDecimals: 6,
    icon: '',
    chain: 'noble',
    coinGeckoId: '',
  },
  uc4e: {
    name: 'C4E',
    coinDenom: 'C4E',
    coinMinimalDenom: 'uc4e',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/chain4energy.png',
    chain: 'chain4energy',
    coinGeckoId: 'chain4energy',
  },
  ufrienzies: {
    coinDenom: 'FRNZ',
    coinMinimalDenom: 'ufrienzies',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/frnz.png',
    chain: 'noble',
    coinGeckoId: '',
  },
  // We are using ibc atom as fee denom on noble added token details for consistency
  'ibc/EF48E6B1A1A19F47ECAEA62F5670C37C0580E86A9E88498B7E393EB6F49F33C0': {
    coinDenom: 'ATOM',
    coinMinimalDenom: 'ibc/EF48E6B1A1A19F47ECAEA62F5670C37C0580E86A9E88498B7E393EB6F49F33C0',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/atom.svg',
    chain: 'noble',
    coinGeckoId: 'cosmos',
  },
  'ibc/0471F1C4E7AFD3F07702BEF6DC365268D64570F7C1FDC98EA6098DD6DE59817B': {
    coinDenom: 'OSMO',
    coinMinimalDenom: 'ibc/0471F1C4E7AFD3F07702BEF6DC365268D64570F7C1FDC98EA6098DD6DE59817B',
    coinDecimals: 6,
    chain: 'quasar',
    coinGeckoId: 'osmo',
    icon: 'https://assets.leapwallet.io/osmo.svg',
  },
  'ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9': {
    coinDenom: 'ATOM',
    coinMinimalDenom: 'ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/atom.svg',
    chain: 'neutron',
    coinGeckoId: 'cosmos',
  },
  usdc: {
    coinDenom: 'USDC',
    coinMinimalDenom: 'uusdc',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/usdc.svg',
    chain: 'noble',
    coinGeckoId: 'usd-coin',
  },
  ulove: {
    coinDenom: 'LOVE',
    coinMinimalDenom: 'ulove',
    coinDecimals: 6,
    icon: '',
    chain: 'noble',
    coinGeckoId: '',
  },
  ukyve: {
    coinDenom: 'KYVE',
    coinMinimalDenom: 'ukyve',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/kyve.svg',
    chain: 'kyve1',
    coinGeckoId: '',
  },
  anom: {
    coinDenom: 'NOM',
    coinMinimalDenom: 'anom',
    coinDecimals: 18,
    coinGeckoId: 'onomy-protocol',
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/onomy/images/nom.png',
    chain: 'onomy',
  },
  uwhale: {
    coinDenom: 'WHALE',
    coinMinimalDenom: 'uwhale',
    coinDecimals: 6,
    coinGeckoId: 'white-whale',
    icon: 'https://assets.leapwallet.io/whitewhale.png',
    chain: 'migaloo',
  },
  uqsr: {
    coinDenom: 'QSR',
    coinMinimalDenom: 'uqsr',
    coinDecimals: 6,
    coinGeckoId: '',
    icon: 'https://raw.githubusercontent.com/ping-pub/explorer/master/public/logos/quasar.png',
    chain: 'quasar',
  },
  untrn: {
    coinDenom: 'NTRN',
    coinMinimalDenom: 'untrn',
    coinDecimals: 6,
    coinGeckoId: 'neutron',
    icon: 'https://assets.leapwallet.io/neutron-logo.jpeg',
    chain: 'neutron',
  },
  utestcore: {
    coinDenom: 'TESTCORE',
    coinMinimalDenom: 'utestcore',
    coinDecimals: 6,
    coinGeckoId: 'core',
    icon: 'https://assets.leapwallet.io/coreum-logo.png',
    chain: 'coreum',
  },
  ucore: {
    coinDenom: 'CORE',
    coinMinimalDenom: 'ucore',
    coinDecimals: 6,
    coinGeckoId: 'core',
    icon: 'https://assets.leapwallet.io/coreum-logo.png',
    chain: 'mainCoreum',
  },
  ubld: {
    coinDenom: 'BLD',
    coinMinimalDenom: 'ubld',
    coinDecimals: 6,
    coinGeckoId: 'bld',
    icon: 'https://assets.leapwallet.io/bld.png',
    chain: 'agoric',
  },
  uist: {
    coinDenom: 'IST',
    coinDecimals: 6,
    coinGeckoId: 'ist',
    coinMinimalDenom: 'uist',
    icon: 'https://assets.leapwallet.io/ist.png',
    chain: 'agoric',
  },
  urun: {
    coinDenom: 'RUN',
    coinMinimalDenom: 'urun',
    coinDecimals: 6,
    coinGeckoId: 'run',
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/agoric/images/run.png',
    chain: 'agoric',
  },
  uakt: {
    coinDenom: 'AKT',
    coinMinimalDenom: 'uakt',
    coinDecimals: 6,
    coinGeckoId: 'akt',
    icon: 'https://assets.leapwallet.io/akt.png',
    chain: 'akash',
  },
  uarkh: {
    coinDenom: 'ARKH',
    coinMinimalDenom: 'uarkh',
    coinDecimals: 6,
    coinGeckoId: 'arkh',
    icon: 'https://www.arkhadian.com/static/images/600-prism.png',
    chain: 'arkh',
  },
  umntl: {
    coinDenom: 'MNTL',
    coinMinimalDenom: 'umntl',
    coinDecimals: 6,
    coinGeckoId: 'mntl',
    icon: 'https://assets.leapwallet.io/mntl.png',
    chain: 'assetmantle',
  },
  uaxl: {
    coinDenom: 'AXL',
    coinMinimalDenom: 'uaxl',
    coinDecimals: 6,
    coinGeckoId: 'axelar',
    icon: 'https://axelarscan.io/logos/assets/axl.png',
    chain: 'axelar',
  },
  uusdc: {
    coinDenom: 'USDC',
    coinMinimalDenom: 'uusdc',
    coinDecimals: 6,
    coinGeckoId: 'axlusdc',
    icon: 'https://assets.leapwallet.io/usdc.svg',
    chain: 'axelar',
  },
  'frax-wei': {
    coinDenom: 'FRAX',
    coinMinimalDenom: 'frax-wei',
    coinDecimals: 18,
    coinGeckoId: 'frax',
    icon: 'https://assets.leapwallet.io/frax.svg',
    chain: 'axelar',
  },
  'dai-wei': {
    coinDenom: 'DAI',
    coinMinimalDenom: 'dai-wei',
    coinDecimals: 18,
    coinGeckoId: 'dai',
    icon: 'https://assets.leapwallet.io/dai.svg',
    chain: 'axelar',
  },
  uusdt: {
    coinDenom: 'USDT',
    coinMinimalDenom: 'uusdt',
    coinDecimals: 6,
    coinGeckoId: 'usdt',
    icon: 'https://assets.leapwallet.io/usdt.svg',
    chain: 'axelar',
  },
  'weth-wei': {
    coinDenom: 'WETH',
    coinMinimalDenom: 'weth-wei',
    coinDecimals: 18,
    coinGeckoId: 'weth',
    icon: 'https://assets.leapwallet.io/weth.png',
    chain: 'axelar',
  },
  'wbtc-satoshi': {
    coinDenom: 'WBTC',
    coinMinimalDenom: 'wbtc-satoshi',
    coinDecimals: 8,
    coinGeckoId: 'wbtc',
    icon: 'https://assets.leapwallet.io/wbtc.png',
    chain: 'axelar',
  },
  ubcna: {
    coinDenom: 'BCNA',
    coinMinimalDenom: 'ubcna',
    coinDecimals: 6,
    coinGeckoId: 'bcna',
    icon: 'https://assets.leapwallet.io/bcna.svg',
    chain: 'bitcanna',
  },
  ubtsg: {
    coinDenom: 'BTSG',
    coinMinimalDenom: 'ubtsg',
    coinDecimals: 6,
    coinGeckoId: 'btsg',
    icon: 'https://assets.leapwallet.io/bitsong.png',
    chain: 'bitsong',
  },
  boot: {
    coinDenom: 'BOOT',
    coinMinimalDenom: 'boot',
    coinDecimals: 0,
    coinGeckoId: 'boot',
    icon: 'https://assets.leapwallet.io/boot.png',
    chain: 'bostrom',
  },
  swth: {
    coinDenom: 'SWTH',
    coinMinimalDenom: 'swth',
    coinDecimals: 8,
    coinGeckoId: 'swth',
    icon: 'https://assets.leapwallet.io/swth.svg',
    chain: 'carbon',
  },
  ucrbrus: {
    coinDenom: 'CRBRUS',
    coinMinimalDenom: 'ucrbrus',
    coinDecimals: 6,
    coinGeckoId: 'crbrus',
    icon: 'https://assets.leapwallet.io/crbrus.png',
    chain: 'cerberus',
  },
  ncheq: {
    coinDenom: 'CHEQ',
    coinMinimalDenom: 'ncheq',
    coinDecimals: 9,
    coinGeckoId: 'cheq',
    icon: 'https://assets.leapwallet.io/cheq.png',
    chain: 'cheqd',
  },
  uhuahua: {
    coinDenom: 'HUAHUA',
    coinMinimalDenom: 'uhuahua',
    coinDecimals: 6,
    coinGeckoId: 'huahua',
    icon: 'https://assets.leapwallet.io/huahua.png',
    chain: 'chihuahua',
  },
  ucht: {
    coinDenom: 'CHT',
    coinMinimalDenom: 'ucht',
    coinDecimals: 6,
    coinGeckoId: 'cht',
    icon: 'https://assets.leapwallet.io/cht.png',
    chain: 'chronicnetwork',
  },
  ucgas: {
    coinDenom: 'CGAS',
    coinMinimalDenom: 'ucgas',
    coinDecimals: 6,
    coinGeckoId: 'cgas',
    icon: 'https://assets.leapwallet.io/cgas.png',
    chain: 'chronicnetwork',
  },
  ucmdx: {
    coinDenom: 'CMDX',
    coinMinimalDenom: 'ucmdx',
    coinDecimals: 6,
    coinGeckoId: 'cmdx',
    icon: 'https://assets.leapwallet.io/cmdx.png',
    chain: 'comdex',
  },
  uatom: {
    coinDenom: 'ATOM',
    coinMinimalDenom: 'uatom',
    coinDecimals: 6,
    coinGeckoId: 'atom',
    icon: 'https://assets.leapwallet.io/atom.png',
    chain: 'cosmos',
  },
  ucre: {
    coinDenom: 'CRE',
    coinMinimalDenom: 'ucre',
    coinDecimals: 6,
    coinGeckoId: 'cre',
    icon: 'https://assets.leapwallet.io/cre.svg',
    chain: 'crescent',
  },
  ubcre: {
    coinDenom: 'bCRE',
    coinMinimalDenom: 'ubcre',
    coinDecimals: 6,
    coinGeckoId: 'liquid-staking-crescent',
    icon: 'https://assets.leapwallet.io/bCRE.svg',
    chain: 'crescent',
  },
  basecro: {
    coinDenom: 'CRO',
    coinMinimalDenom: 'basecro',
    coinDecimals: 8,
    coinGeckoId: 'cro',
    icon: 'https://assets.leapwallet.io/cronos.png',
    chain: 'cryptoorgchain',
  },
  acudos: {
    coinDenom: 'CUDOS',
    coinMinimalDenom: 'acudos',
    coinDecimals: 18,
    coinGeckoId: 'cudos',
    icon: 'https://assets.leapwallet.io/cudos.svg',
    chain: 'cudos',
  },
  udec: {
    coinDenom: 'DEC',
    coinMinimalDenom: 'udec',
    coinDecimals: 6,
    coinGeckoId: 'dec',
    icon: 'https://assets.leapwallet.io/dec.png',
    chain: 'decentr',
  },
  udsm: {
    coinDenom: 'DSM',
    coinMinimalDenom: 'udsm',
    coinDecimals: 6,
    coinGeckoId: 'dsm',
    icon: 'https://assets.leapwallet.io/dsm.svg',
    chain: 'desmos',
  },
  udig: {
    coinDenom: 'DIG',
    coinMinimalDenom: 'udig',
    coinDecimals: 6,
    coinGeckoId: 'dig',
    icon: 'https://assets.leapwallet.io/dig.png',
    chain: 'dig',
  },
  aechelon: {
    coinDenom: 'ECH',
    coinMinimalDenom: 'aechelon',
    coinDecimals: 18,
    coinGeckoId: 'echelon',
    icon: 'https://assets.leapwallet.io/ech.png',
    chain: 'echelon',
  },
  ungm: {
    coinDenom: 'NGM',
    coinMinimalDenom: 'ungm',
    coinDecimals: 6,
    coinGeckoId: 'ngm',
    icon: 'https://assets.leapwallet.io/ngm.png',
    chain: 'emoney',
  },
  eeur: {
    coinDenom: 'EEUR',
    coinMinimalDenom: 'eeur',
    coinDecimals: 6,
    coinGeckoId: 'eeur',
    icon: 'https://assets.leapwallet.io/eeur.png',
    chain: 'emoney',
  },
  aevmos: {
    coinDenom: 'EVMOS',
    coinMinimalDenom: 'aevmos',
    coinDecimals: 18,
    coinGeckoId: 'evmos',
    icon: 'https://assets.leapwallet.io/evmos.svg',
    chain: 'evmos',
  },
  afet: {
    coinDenom: 'FET',
    coinMinimalDenom: 'afet',
    coinDecimals: 18,
    coinGeckoId: 'fet',
    icon: 'https://assets.leapwallet.io/fet.png',
    chain: 'fetchhub',
  },
  nanomobx: {
    coinDenom: 'MOBX',
    coinMinimalDenom: 'nanomobx',
    coinDecimals: 9,
    coinGeckoId: 'mobx',
    icon: 'https://assets.leapwallet.io/mobx.svg',
    chain: 'fetchhub',
  },
  ufct: {
    coinDenom: 'FCT',
    coinMinimalDenom: 'ufct',
    coinDecimals: 6,
    coinGeckoId: 'fct',
    icon: 'https://assets.leapwallet.io/fct.svg',
    chain: 'firmachain',
  },
  uglx: {
    coinDenom: 'GLX',
    coinMinimalDenom: 'uglx',
    coinDecimals: 6,
    coinGeckoId: 'glx',
    icon: 'https://assets.leapwallet.io/glx.svg',
    chain: 'galaxy',
  },
  el1: {
    coinDenom: 'L1',
    coinMinimalDenom: 'el1',
    coinDecimals: 18,
    coinGeckoId: 'l1',
    icon: 'https://assets.leapwallet.io/l1.svg',
    chain: 'genesisl1',
  },
  ugraviton: {
    coinDenom: 'GRAV',
    coinMinimalDenom: 'ugraviton',
    coinDecimals: 6,
    coinGeckoId: 'grav',
    icon: 'https://assets.leapwallet.io/grav.svg',
    chain: 'gravitybridge',
  },
  gravity0xfB5c6815cA3AC72Ce9F5006869AE67f18bF77006: {
    coinDenom: 'PSTAKE',
    coinMinimalDenom: 'gravity0xfB5c6815cA3AC72Ce9F5006869AE67f18bF77006',
    coinDecimals: 6,
    coinGeckoId: 'pstake',
    icon: 'https://assets.leapwallet.io/pstake.png',
    chain: 'gravitybridge',
  },
  idep: {
    coinDenom: 'IDEP',
    coinMinimalDenom: 'idep',
    coinDecimals: 6,
    coinGeckoId: 'IDEP',
    icon: 'https://assets.leapwallet.io/idep.svg',
    chain: 'idep',
  },
  uixo: {
    coinDenom: 'IXO',
    coinMinimalDenom: 'uixo',
    coinDecimals: 6,
    coinGeckoId: 'ixo',
    icon: 'https://assets.leapwallet.io/ixo.png',
    chain: 'impacthub',
  },
  inj: {
    coinDenom: 'INJ',
    coinMinimalDenom: 'inj',
    coinDecimals: 18,
    coinGeckoId: 'inj',
    icon: 'https://assets.leapwallet.io/inj.png',
    chain: 'injective',
  },
  uiris: {
    coinDenom: 'IRIS',
    coinMinimalDenom: 'uiris',
    coinDecimals: 6,
    coinGeckoId: 'iris',
    icon: 'https://assets.leapwallet.io/iris.png',
    chain: 'irisnet',
  },
  ujuno: {
    coinDenom: 'JUNO',
    coinMinimalDenom: 'ujuno',
    coinDecimals: 6,
    coinGeckoId: 'juno',
    icon: 'https://assets.leapwallet.io/juno.svg',
    chain: 'juno',
  },
  ukava: {
    coinDenom: 'KAVA',
    coinMinimalDenom: 'ukava',
    coinDecimals: 6,
    coinGeckoId: 'kava',
    icon: 'https://assets.leapwallet.io/kava.png',
    chain: 'kava',
  },
  hard: {
    coinDenom: 'HARD',
    coinMinimalDenom: 'hard',
    coinDecimals: 6,
    coinGeckoId: 'HARD',
    icon: 'https://assets.leapwallet.io/hard.svg',
    chain: 'kava',
  },
  swp: {
    coinDenom: 'SWP',
    coinMinimalDenom: 'swp',
    coinDecimals: 6,
    coinGeckoId: 'SWP',
    icon: 'https://assets.leapwallet.io/swp.svg',
    chain: 'kava',
  },
  udarc: {
    coinDenom: 'DARC',
    coinMinimalDenom: 'udarc',
    coinDecimals: 6,
    coinGeckoId: 'darc',
    icon: 'https://assets.leapwallet.io/darc.svg',
    chain: 'konstellation',
  },
  ukuji: {
    coinDenom: 'KUJI',
    coinMinimalDenom: 'ukuji',
    coinDecimals: 6,
    coinGeckoId: 'kuji',
    icon: 'https://assets.leapwallet.io/kuji.png',
    chain: 'kujira',
  },
  'factory/kujira1qk00h5atutpsv900x202pxx42npjr9thg58dnqpa72f2p7m2luase444a7/uusk': {
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/kujira/images/usk.png',
    coinDenom: 'USK',
    coinMinimalDenom: 'factory/kujira1qk00h5atutpsv900x202pxx42npjr9thg58dnqpa72f2p7m2luase444a7/uusk',
    coinDecimals: 6,
    coinGeckoId: 'usk',
    chain: 'kujira',
  },
  nanolike: {
    coinDenom: 'LIKE',
    coinMinimalDenom: 'nanolike',
    coinDecimals: 9,
    coinGeckoId: 'like',
    icon: 'https://assets.leapwallet.io/like.svg',
    chain: 'likecoin',
  },
  aLYT: {
    coinDenom: 'LYT',
    coinMinimalDenom: 'aLYT',
    coinDecimals: 18,
    coinGeckoId: 'LYT',
    icon: 'https://assets.leapwallet.io/lyt.svg',
    chain: 'logos',
  },
  ulum: {
    coinDenom: 'LUM',
    coinMinimalDenom: 'ulum',
    coinDecimals: 6,
    coinGeckoId: 'lum',
    icon: 'https://assets.leapwallet.io/lum.svg',
    chain: 'lumnetwork',
  },
  umeme: {
    coinDenom: 'MEME',
    coinMinimalDenom: 'umeme',
    coinDecimals: 6,
    coinGeckoId: 'meme',
    icon: 'https://assets.leapwallet.io/meme.svg',
    chain: 'meme',
  },
  utick: {
    coinDenom: 'TICK',
    coinMinimalDenom: 'utick',
    coinDecimals: 6,
    coinGeckoId: 'tick',
    icon: 'https://assets.leapwallet.io/tick.svg',
    chain: 'microtick',
  },
  aMYT: {
    coinDenom: 'MYT',
    coinMinimalDenom: 'aMYT',
    coinDecimals: 18,
    coinGeckoId: 'MYT',
    icon: 'https://assets.leapwallet.io/mythos.svg',
    chain: 'mythos',
  },
  uocta: {
    coinDenom: 'OCTA',
    coinMinimalDenom: 'uocta',
    coinDecimals: 6,
    coinGeckoId: 'octa',
    icon: 'https://assets.leapwallet.io/octa.svg',
    chain: 'octa',
  },
  loki: {
    name: 'ODIN',
    coinDenom: 'ODIN',
    coinMinimalDenom: 'loki',
    coinDecimals: 6,
    coinGeckoId: 'odin-protocol',
    icon: 'https://assets.leapwallet.io/odin.png',
    chain: 'odin',
  },
  uflix: {
    coinDenom: 'FLIX',
    coinMinimalDenom: 'uflix',
    coinDecimals: 6,
    coinGeckoId: 'flix',
    icon: 'https://assets.leapwallet.io/flix.png',
    chain: 'omniflixhub',
  },
  orai: {
    coinDenom: 'ORAI',
    coinMinimalDenom: 'orai',
    coinDecimals: 6,
    coinGeckoId: 'oraichain-token',
    icon: 'https://assets.leapwallet.io/orai.svg',
    chain: 'oraichain',
  },
  uosmo: {
    coinDenom: 'OSMO',
    coinMinimalDenom: 'uosmo',
    coinDecimals: 6,
    coinGeckoId: 'osmo',
    icon: 'https://assets.leapwallet.io/osmo.svg',
    chain: 'osmosis',
  },
  uion: {
    coinDenom: 'ION',
    coinMinimalDenom: 'uion',
    coinDecimals: 6,
    coinGeckoId: 'ion',
    icon: 'https://assets.leapwallet.io/ion.svg',
    chain: 'osmosis',
  },
  umed: {
    coinDenom: 'MED',
    coinMinimalDenom: 'umed',
    coinDecimals: 6,
    coinGeckoId: 'med',
    icon: 'https://assets.leapwallet.io/med.png',
    chain: 'panacea',
  },
  uxprt: {
    coinDenom: 'XPRT',
    coinMinimalDenom: 'uxprt',
    coinDecimals: 6,
    coinGeckoId: 'xprt',
    icon: 'https://assets.leapwallet.io/xprt.png',
    chain: 'persistence',
  },
  uqstars: {
    coinDenom: 'qSTARS',
    coinMinimalDenom: 'uqstars',
    coinDecimals: 6,
    coinGeckoId: '',
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qstars.png',
    chain: 'quicksilver',
  },
  uqregen: {
    coinDenom: 'qREGEN',
    coinMinimalDenom: 'uqregen',
    coinDecimals: 6,
    coinGeckoId: '',
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qregen.png',
    chain: 'quicksilver',
  },
  uqck: {
    coinDenom: 'QCK',
    coinMinimalDenom: 'uqck',
    coinDecimals: 6,
    coinGeckoId: 'quicksilver',
    icon: 'https://assets.leapwallet.io/qck.png',
    chain: 'quicksilver',
  },
  uqatom: {
    coinDenom: 'qATOM',
    coinMinimalDenom: 'uqatom',
    coinDecimals: 6,
    coinGeckoId: '',
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qatom.png',
    chain: 'quicksilver',
  },
  uqosmo: {
    coinDenom: 'qOSMO',
    coinMinimalDenom: 'uqosmo',
    coinDecimals: 6,
    coinGeckoId: '',
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qosmo.png',
    chain: 'quicksilver',
  },
  uregen: {
    coinDenom: 'REGEN',
    coinMinimalDenom: 'uregen',
    coinDecimals: 6,
    coinGeckoId: 'regen',
    icon: 'https://assets.leapwallet.io/regen.png',
    chain: 'regen',
  },
  uatolo: {
    coinDenom: 'ATOLO',
    coinMinimalDenom: 'uatolo',
    coinDecimals: 6,
    coinGeckoId: 'atolo',
    icon: 'https://assets.leapwallet.io/atolo.svg',
    chain: 'rizon',
  },
  uscrt: {
    coinDenom: 'SCRT',
    coinMinimalDenom: 'uscrt',
    coinDecimals: 6,
    coinGeckoId: 'scrt',
    icon: 'https://assets.leapwallet.io/scrt.svg',
    chain: 'secret',
  },
  uctk: {
    coinDenom: 'CTK',
    coinMinimalDenom: 'uctk',
    coinDecimals: 6,
    coinGeckoId: 'ctk',
    icon: 'https://assets.leapwallet.io/ctk.png',
    chain: 'shentu',
  },
  rowan: {
    coinDenom: 'ROWAN',
    coinMinimalDenom: 'rowan',
    coinDecimals: 18,
    coinGeckoId: 'erowan',
    icon: 'https://assets.leapwallet.io/rowan.svg',
    chain: 'sifchain',
  },
  usomm: {
    coinDenom: 'SOMM',
    coinMinimalDenom: 'usomm',
    coinDecimals: 6,
    coinGeckoId: 'somm',
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/sommelier/images/somm.svg',
    chain: 'sommelier',
  },
  ustars: {
    coinDenom: 'STARS',
    coinMinimalDenom: 'ustars',
    coinDecimals: 6,
    coinGeckoId: 'stars',
    icon: 'https://assets.leapwallet.io/stars.png',
    chain: 'stargaze',
  },
  uiov: {
    coinDenom: 'IOV',
    coinMinimalDenom: 'uiov',
    coinDecimals: 6,
    coinGeckoId: 'iov',
    icon: 'https://assets.leapwallet.io/iov.svg',
    chain: 'starname',
  },
  uluna: {
    coinDenom: 'LUNA',
    coinMinimalDenom: 'uluna',
    coinDecimals: 6,
    coinGeckoId: 'luna',
    icon: 'https://assets.leapwallet.io/luna.png',
    chain: 'terra',
  },
  // uusd: {
  //   coinDenom: 'USTC',
  //   coinMinimalDenom: 'uusd',
  //   coinDecimals: 6,
  //   coinGeckoId: 'ust',
  //   icon: 'https://assets.leapwallet.io/ust.svg',
  //   chain: 'terra',
  // },
  ukrw: {
    coinDenom: 'KRTC',
    coinMinimalDenom: 'ukrw',
    coinDecimals: 6,
    coinGeckoId: 'krt',
    icon: 'https://assets.leapwallet.io/krt.svg',
    chain: 'terra',
  },
  uaud: {
    coinDenom: 'AUTC',
    coinMinimalDenom: 'uaud',
    coinDecimals: 6,
    coinGeckoId: 'aut',
    icon: 'https://assets.leapwallet.io/aut.svg',
    chain: 'terra',
  },
  ucad: {
    coinDenom: 'CATC',
    coinMinimalDenom: 'ucad',
    coinDecimals: 6,
    coinGeckoId: 'cat',
    icon: 'https://assets.leapwallet.io/cat.svg',
    chain: 'terra',
  },
  uchf: {
    coinDenom: 'CHTC',
    coinMinimalDenom: 'uchf',
    coinDecimals: 6,
    coinGeckoId: 'cht',
    icon: 'https://assets.leapwallet.io/cht.svg',
    chain: 'terra',
  },
  ucny: {
    coinDenom: 'CNTC',
    coinMinimalDenom: 'ucny',
    coinDecimals: 6,
    coinGeckoId: 'cnt',
    icon: 'https://assets.leapwallet.io/cnt.svg',
    chain: 'terra',
  },
  udkk: {
    coinDenom: 'DKTC',
    coinMinimalDenom: 'udkk',
    coinDecimals: 6,
    coinGeckoId: 'dkt',
    icon: 'https://assets.leapwallet.io/dkt.svg',
    chain: 'terra',
  },
  ueur: {
    coinDenom: 'EUTC',
    coinMinimalDenom: 'ueur',
    coinDecimals: 6,
    coinGeckoId: 'eut',
    icon: 'https://assets.leapwallet.io/eut.svg',
    chain: 'terra',
  },
  ugbp: {
    coinDenom: 'GBTC',
    coinMinimalDenom: 'ugbp',
    coinDecimals: 6,
    coinGeckoId: 'gbt',
    icon: 'https://assets.leapwallet.io/gbt.svg',
    chain: 'terra',
  },
  uhkd: {
    coinDenom: 'HKTC',
    coinMinimalDenom: 'uhkd',
    coinDecimals: 6,
    coinGeckoId: 'hkt',
    icon: 'https://assets.leapwallet.io/hkt.svg',
    chain: 'terra',
  },
  uidr: {
    coinDenom: 'IDTC',
    coinMinimalDenom: 'uidr',
    coinDecimals: 6,
    coinGeckoId: 'idt',
    icon: 'https://assets.leapwallet.io/idt.svg',
    chain: 'terra',
  },
  uinr: {
    coinDenom: 'INTC',
    coinMinimalDenom: 'uinr',
    coinDecimals: 6,
    coinGeckoId: 'int',
    icon: 'https://assets.leapwallet.io/int.svg',
    chain: 'terra',
  },
  ujpy: {
    coinDenom: 'JPTC',
    coinMinimalDenom: 'ujpy',
    coinDecimals: 6,
    coinGeckoId: 'jpt',
    icon: 'https://assets.leapwallet.io/jpt.svg',
    chain: 'terra',
  },
  umnt: {
    coinDenom: 'MNTC',
    coinMinimalDenom: 'umnt',
    coinDecimals: 6,
    coinGeckoId: 'mnt',
    icon: 'https://assets.leapwallet.io/mnt.svg',
    chain: 'terra',
  },
  umyr: {
    coinDenom: 'MYTC',
    coinMinimalDenom: 'umyr',
    coinDecimals: 6,
    coinGeckoId: 'myt',
    icon: 'https://assets.leapwallet.io/myt.svg',
    chain: 'terra',
  },
  unok: {
    coinDenom: 'NOTC',
    coinMinimalDenom: 'unok',
    coinDecimals: 6,
    coinGeckoId: 'not',
    icon: 'https://assets.leapwallet.io/not.svg',
    chain: 'terra',
  },
  uphp: {
    coinDenom: 'PHTC',
    coinMinimalDenom: 'uphp',
    coinDecimals: 6,
    coinGeckoId: 'pht',
    icon: 'https://assets.leapwallet.io/pht.svg',
    chain: 'terra',
  },
  usdr: {
    coinDenom: 'SDTC',
    coinMinimalDenom: 'usdr',
    coinDecimals: 6,
    coinGeckoId: 'sdt',
    icon: 'https://assets.leapwallet.io/sdt.svg',
    chain: 'terra',
  },
  usek: {
    coinDenom: 'SETC',
    coinMinimalDenom: 'usek',
    coinDecimals: 6,
    coinGeckoId: 'set',
    icon: 'https://assets.leapwallet.io/set.svg',
    chain: 'terra',
  },
  usgd: {
    coinDenom: 'SGTC',
    coinMinimalDenom: 'usgd',
    coinDecimals: 6,
    coinGeckoId: 'sgt',
    icon: 'https://assets.leapwallet.io/sgt.svg',
    chain: 'terra',
  },
  uthb: {
    coinDenom: 'THTC',
    coinMinimalDenom: 'uthb',
    coinDecimals: 6,
    coinGeckoId: 'tht',
    icon: 'https://assets.leapwallet.io/tht.svg',
    chain: 'terra',
  },
  utwd: {
    coinDenom: 'TWTC',
    coinMinimalDenom: 'utwd',
    coinDecimals: 6,
    coinGeckoId: 'twt',
    icon: 'https://assets.leapwallet.io/twt.svg',
    chain: 'terra',
  },
  uumee: {
    coinDenom: 'UMEE',
    coinMinimalDenom: 'uumee',
    coinDecimals: 6,
    coinGeckoId: 'umee',
    icon: 'https://assets.leapwallet.io/umee.png',
    chain: 'umee',
  },
  uvdl: {
    coinDenom: 'VDL',
    coinMinimalDenom: 'uvdl',
    coinDecimals: 6,
    coinGeckoId: 'vdl',
    icon: 'https://assets.leapwallet.io/vdl.svg',
    chain: 'vidulum',
  },
  ujunox: {
    coinDenom: 'JUNO',
    coinMinimalDenom: 'ujunox',
    coinDecimals: 6,
    coinGeckoId: 'juno',
    icon: 'https://assets.leapwallet.io/juno.svg',
    chain: 'juno',
  },
  umars: {
    coinDenom: 'MARS',
    coinMinimalDenom: 'umars',
    coinDecimals: 6,
    coinGeckoId: 'mars',
    icon: 'https://marsprotocol.io/MARSTokenMini.svg',
    chain: 'mars',
  },
  usei: {
    coinDenom: 'SEI',
    coinMinimalDenom: 'usei',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/sei.png',
    chain: 'sei',
    coinGeckoId: 'sei',
  },
  'factory/sei1466nf3zuxpya8q9emxukd7vftaf6h4psr0a07srl5zw74zh84yjqpeheyc/uust2': {
    icon: 'https://trade.vortexprotocol.io/images/tokens/UST2.png',
    coinDenom: 'UST2',
    coinMinimalDenom: 'factory/sei1466nf3zuxpya8q9emxukd7vftaf6h4psr0a07srl5zw74zh84yjqpeheyc/uust2',
    coinDecimals: 6,
    coinGeckoId: 'ust2',
    chain: 'sei',
  },
  'factory/sei1jdppe6fnj2q7hjsepty5crxtrryzhuqsjrj95y/uust2': {
    icon: 'https://trade.vortexprotocol.io/images/tokens/UST2.png',
    coinDenom: 'UST2',
    coinMinimalDenom: 'factory/sei1jdppe6fnj2q7hjsepty5crxtrryzhuqsjrj95y/uust2',
    coinDecimals: 6,
    coinGeckoId: '',
    chain: 'seiTestnet2',
  },
  'factory/sei1jdppe6fnj2q7hjsepty5crxtrryzhuqsjrj95y/psei': {
    icon: '',
    coinDenom: 'PSEI',
    coinMinimalDenom: 'factory/sei1jdppe6fnj2q7hjsepty5crxtrryzhuqsjrj95y/psei',
    coinDecimals: 0,
    coinGeckoId: '',
    chain: 'seiTestnet2',
  },
  ustrd: {
    coinDenom: 'STRD',
    coinMinimalDenom: 'ustrd',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/strd.png',
    chain: 'stride',
    coinGeckoId: 'strd',
  },
  stinj: {
    coinDenom: 'stINJ',
    coinMinimalDenom: 'stinj',
    coinDecimals: 18,
    icon: 'https://assets.leapwallet.io/stinj.png',
    chain: 'injective',
    coinGeckoId: 'injective',
  },
  stuosmo: {
    coinDenom: 'stOSMO',
    coinMinimalDenom: 'stuosmo',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/stosmo.png',
    chain: 'osmosis',
    coinGeckoId: 'osmosis',
  },
  stustars: {
    coinDenom: 'stSTARS',
    coinMinimalDenom: 'stustars',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/ststars.png',
    chain: 'stargaze',
    coinGeckoId: 'stars',
  },
  stuluna: {
    coinDenom: 'stLUNA',
    coinMinimalDenom: 'stuluna',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/stluna.png',
    chain: 'terra',
    coinGeckoId: 'luna',
  },
  staevmos: {
    coinDenom: 'stEVMOS',
    coinMinimalDenom: 'staevmos',
    coinDecimals: 18,
    icon: 'https://assets.leapwallet.io/stevmos.png',
    chain: 'evmos',
    coinGeckoId: 'evmos',
  },
  stuatom: {
    coinDenom: 'stATOM',
    coinMinimalDenom: 'stuatom',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/statom.png',
    chain: 'cosmos',
    coinGeckoId: 'atom',
  },
  stujuno: {
    coinDenom: 'stJUNO',
    coinMinimalDenom: 'stujuno',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/stjuno.png',
    chain: 'juno',
    coinGeckoId: 'juno',
  },
  utori: {
    coinDenom: 'TORI',
    coinMinimalDenom: 'utori',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/teritori.png',
    chain: 'teritori',
    coinGeckoId: 'tori',
  },
  ujkl: {
    coinDenom: 'JKL',
    coinMinimalDenom: 'ujkl',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/jkl.png',
    chain: 'jackal',
    coinGeckoId: 'jkl',
  },
  acanto: {
    coinDenom: 'CANTO',
    coinMinimalDenom: 'acanto',
    coinDecimals: 18,
    icon: 'https://assets.leapwallet.io/canto.png',
    chain: 'canto',
    coinGeckoId: 'canto',
  },
  upasg: {
    coinDenom: 'PASG',
    coinMinimalDenom: 'upasg',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/pasg.png',
    chain: 'passage',
    coinGeckoId: '',
  },
  uconst: {
    coinDenom: 'CONST',
    coinMinimalDenom: 'uconst',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/archway.png',
    chain: 'const',
    coinGeckoId: 'const',
  },
  aconst: {
    coinDenom: 'CONST',
    coinMinimalDenom: 'aconst',
    coinDecimals: 18,
    icon: 'https://assets.leapwallet.io/archway.svg',
    chain: 'archway',
    coinGeckoId: 'const',
  },
  aarch: {
    coinDecimals: 18,
    coinDenom: 'ARCH',
    coinGeckoId: '',
    coinMinimalDenom: 'aarch',
    icon: 'https://assets.leapwallet.io/archway.svg',
    chain: 'archway',
  },
  ulore: {
    coinDenom: 'LORE',
    coinMinimalDenom: 'ulore',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/gitopia.png',
    chain: 'gitopia',
    coinGeckoId: 'gitopia',
  },
  ubze: {
    coinDenom: 'BZE',
    coinMinimalDenom: 'ubze',
    coinDecimals: 6,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/beezee/images/bze.png',
    chain: 'beezee',
    coinGeckoId: 'beezee',
  },
  'dot-planck': {
    coinDenom: 'DOT',
    coinMinimalDenom: 'dot-plank',
    coinDecimals: 10,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/polkadot/images/dot.png',
    chain: 'axelar',
    coinGeckoId: 'polkadot',
  },
  mGeo: {
    coinDenom: 'GEO',
    coinMinimalDenom: 'mGeo',
    coinDecimals: 6,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/odin/images/geo.png',
    chain: 'odin',
    coinGeckoId: '',
  },
  ulamb: {
    coinDenom: 'LAMB',
    coinMinimalDenom: 'ulamb',
    coinDecimals: 18,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/lambda/images/lambda.png',
    chain: 'Lambda',
    coinGeckoId: 'lambda',
  },
  'link-wei': {
    coinDenom: 'LINK',
    coinMinimalDenom: 'link-wei',
    coinDecimals: 18,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/link.png',
    chain: 'axelar',
    coinGeckoId: 'chainlink',
  },
  'wmatic-wei': {
    coinDenom: 'WMATIC',
    coinMinimalDenom: 'wmatic-wei',
    coinDecimals: 18,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/polygon/images/wmatic.png',
    chain: 'axelar',
    coinGeckoId: 'matic-network',
  },
  'wbnb-wei': {
    coinDenom: 'WBNB',
    coinMinimalDenom: 'wbnb-wei',
    coinDecimals: 18,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/binancesmartchain/images/wbnb.png',
    chain: 'axelar',
    coinGeckoId: 'wbnb',
  },
  utgd: {
    coinDenom: 'TGD',
    coinMinimalDenom: 'utgd',
    coinDecimals: 6,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/tgrade/images/tgrade-symbol-gradient.png',
    chain: 'tgrade',
    coinGeckoId: 'tgrade',
  },
  'mkr-wei': {
    coinDenom: 'MKR',
    coinMinimalDenom: 'mkr-wei',
    coinDecimals: 18,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/mkr.svg',
    chain: 'axelar',
    coinGeckoId: 'maker',
  },
  tkyve: {
    coinDenom: 'KYVE',
    coinMinimalDenom: 'tkyve',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/kyve.svg',
    chain: 'kyve',
    coinGeckoId: 'kyve-network',
  },
  aplanq: {
    coinDenom: 'PLQ',
    coinMinimalDenom: 'aplanq',
    coinDecimals: 18,
    icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/planq/images/planq.svg',
    chain: 'planq',
    coinGeckoId: 'planq',
  },
  ppica: {
    coinDenom: 'PICA',
    coinMinimalDenom: 'ppica',
    coinDecimals: 12,
    icon: 'https://assets.leapwallet.io/pica.svg',
    chain: 'composable',
    coinGeckoId: 'picasso',
  },
  unom: {
    coinDenom: 'NOM',
    coinMinimalDenom: 'unom',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/nomic-logo.svg',
    chain: 'nomic',
    coinGeckoId: '',
  },
  unls: {
    coinDenom: 'NLS',
    coinMinimalDenom: 'unls',
    coinDecimals: 6,
    icon: 'https://nolus.io/theme/assets/images/nolus_token.ae04133d4ccbfd2e6db8.png',
    chain: 'nolus',
    coinGeckoId: '',
  },
  aheart: {
    name: 'HEART',
    coinDenom: 'HEART',
    coinDecimals: 18,
    coinMinimalDenom: 'aheart',
    icon: 'https://assets.leapwallet.io/humans.png',
    chain: 'humans',
    coinGeckoId: 'humans-ai',
  },
  ulava: {
    coinDenom: 'LAVA',
    coinMinimalDenom: 'ulava',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/lava.png',
    chain: 'lava',
    coinGeckoId: '',
  },
  uom: {
    coinDenom: 'OM',
    coinMinimalDenom: 'uom',
    coinDecimals: 6,
    icon: 'https://assets.leapwallet.io/mantra.png',
    chain: 'mantra',
    coinGeckoId: '',
  },
  ...Cw20Denoms.juno,
  ...Cw20Denoms.secret,
};
