export type SecretToken = {
  name: string;
  symbol: string;
  decimals: number;
  icon: string;
  coingeckoId?: string;
  chain?: string;
  snip24Enabled?: boolean;
};

export const SnipDenoms: Record<string, SecretToken> = {
  secret1k0jntykt7e4g3y88ltc60czgjuqdy4c9e8fzek: {
    name: 'sSecret',
    symbol: 'sSCRT',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/scrt.svg',
    coingeckoId: 'scrt',
    chain: 'secret',
  },
  secret14mzwd0ps5q277l20ly2q3aetqe3ev4m4260gf4: {
    name: 'Secret ATOM',
    symbol: 'sATOM',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/atom.png',
    coingeckoId: 'atom',
    chain: 'cosmos',
    snip24Enabled: true,
  },
  secret1zwwealwm0pcl9cul4nt6f38dsy6vzplw8lp3qg: {
    name: 'Secret OSMO',
    symbol: 'sOSMO',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/osmo.png',
    coingeckoId: 'osmo',
    chain: 'osmosis',
    snip24Enabled: true,
  },
  secret1smmc5k24lcn4j2j8f3w0yaeafga6wmzl0qct03: {
    name: 'Secret JUNO',
    symbol: 'sJUNO',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/juno.svg',
    snip24Enabled: true,
    chain: 'juno',
    coingeckoId: 'juno',
  },
  secret1x0dqckf2khtxyrjwhlkrx9lwwmz44k24vcv2vv: {
    name: 'Secret STARS',
    symbol: 'sSTARS',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/stars.png',
    coingeckoId: 'stars',
    chain: 'stargaze',
    snip24Enabled: true,
  },
  secret1gaew7k9tv4hlx2f4wq4ta4utggj4ywpkjysqe8: {
    name: 'Secret KUJI',
    symbol: 'sKUJI',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/kuji.png',
    snip24Enabled: true,
    chain: 'kujira',
    coingeckoId: 'kuji',
  },
  secret16cwf53um7hgdvepfp3jwdzvwkt5qe2f9vfkuwv: {
    name: 'Secret INJ',
    symbol: 'sINJ',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/inj.png',
    snip24Enabled: true,
    chain: 'injective',
    coingeckoId: 'inj',
  },
  secret1dtghxvrx35nznt8es3fwxrv4qh56tvxv22z79d: {
    name: 'Secret GRAV',
    symbol: 'sGRAV',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/grav.png',
    snip24Enabled: true,
    chain: 'gravitybridge',
    coingeckoId: 'grav',
  },
  secret1grg9unv2ue8cf98t50ea45prce7gcrj2n232kq: {
    name: 'Secret EVMOS',
    symbol: 'sEVMOS',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/evmos.svg',
    snip24Enabled: true,
    chain: 'evmos',
    coingeckoId: 'evmos',
  },
  secret1tatdlkyznf00m3a7hftw5daaq2nk38ugfphuyr: {
    name: 'Secret CRE',
    symbol: 'sCRE',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/cre.png',
    snip24Enabled: true,
    chain: 'crescent',
    coingeckoId: 'cre',
  },
  secret168j5f78magfce5r2j4etaytyuy7ftjkh4cndqw: {
    name: 'Secret AKT',
    symbol: 'sAKT',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/akt.png',
    chain: 'akash',
    coingeckoId: 'akt',
  },
  secret159p22zvq2wzsdtqhm2plp4wg33srxp2hf0qudc: {
    name: 'Secret ROWAN',
    symbol: 'sROWAN',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/rowan.png',
    snip24Enabled: true,
    chain: 'sifchain',
    coingeckoId: 'rowan',
  },
  secret17gg8xcx04ldqkvkrd7r9w60rdae4ck8aslt9cf: {
    name: 'Secret STRD',
    symbol: 'sSTRD',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/strd.png',
    snip24Enabled: true,
    chain: 'stride',
    coingeckoId: 'strd',
  },
  secret1xcrf2vvxcz8dhtgzgsd0zmzlf9g320ea2rhdjw: {
    name: 'Secret ChainLink Token',
    symbol: 'sLINK',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/link_ethereum.svg',
  },
  secret13j9sg2lpmwl92taac4lr3xqhslnm2yjm4nsmzl: {
    name: 'Secret RENBTC',
    symbol: 'sRNBTC',
    decimals: 8,
    icon: 'https://assets.leapwallet.io/secret-tokens/renbtc_ethereum.svg',
  },
  secret1vnjck36ld45apf8u4fedxd5zy7f5l92y3w5qwq: {
    name: 'Secret Dai Stablecoin',
    symbol: 'sDAI',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/dai_ethereum.svg',
  },
  secret15grq8y54tvc24j8hf8chunsdcr84fd3d30fvqv: {
    name: 'Secret yearn.finance',
    symbol: 'sYFI',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/yfi_ethereum.svg',
  },
  secret1wuzzjsdhthpvuyeeyhfq2ftsn3mvwf9rxy6ykw: {
    name: 'Secret Ethereum',
    symbol: 'sETH',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/eth_ethereum.svg',
  },
  secret1vcm525c3gd9g5ggfqg7d20xcjnmcc8shh902un: {
    name: 'Secret ReserveRights',
    symbol: 'sRSR',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/rsr_ethereum.svg',
  },
  secret1h6z05y90gwm4sqxzhz4pkyp36cna9xtp7q0urv: {
    name: 'Secret USDC',
    symbol: 'sUSDC',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/usdc_ethereum.svg',
  },
  secret1ukn328k6y3th5nw9z00p8lvk5s7m05cr9p06cu: {
    name: 'Secret DefiPulseIndex',
    symbol: 'sDPI',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/dpi_ethereum.svg',
  },
  secret1ds8850j99cf5h3hygy25f0zzs6r6s7vsgfs8te: {
    name: 'Secret Uniswap',
    symbol: 'sUNI',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/uni_ethereum.svg',
  },
  secret18wpjn83dayu4meu6wnn29khfkwdxs7kyrz9c8f: {
    name: 'Secret Tether',
    symbol: 'sUSDT',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/usdt_ethereum.svg',
  },
  secret1g7jfnxmxkjgqdts9wlmn238mrzxz5r92zwqv4a: {
    name: 'Secret Wrapped BTC',
    symbol: 'sWBTC',
    decimals: 8,
    icon: 'https://assets.leapwallet.io/secret-tokens/wbtc_ethereum.svg',
  },
  secret12sjaw9wutn39cc5wqxfmkypm4n7tcerwfpvmps: {
    name: 'Secret Ocean Token',
    symbol: 'sOCEAN',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/ocean_ethereum.svg',
  },
  secret1gv6l62pfzaauyl0sjznczjdxk3x4ez2sfm3hx8: {
    name: 'SecretPugaCoin',
    symbol: 'PGC',
    decimals: 6,
    icon: '',
  },
  secret1r0l0g7l07y7xrpyys80z3qu2eqvnfjlpcees2x: {
    name: 'ScrtMoon',
    symbol: 'sMOON',
    decimals: 6,
    icon: '',
  },
  secret1vp5vrl0wacxlkh03xkcvfh6q9tcrw4qrl4q4a5: {
    name: 'Secret Alt',
    symbol: 'sALT',
    decimals: 6,
    icon: '',
  },
  secret1ryh523y4e3233hphrkdslegszqz8syjfpthcpp: {
    name: 'Secret TrueUSD',
    symbol: 'sTUSD',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/tusd_ethereum.svg',
  },
  secret19uje5xy80rm6rfu03df2xea532mcalw9hv8vf9: {
    name: 'Secret Sushi',
    symbol: 'sSUSHI',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/sushi_ethereum.svg',
  },
  secret1xzlgeyuuyqje79ma6vllregprkmgwgavk8y798: {
    name: 'fatsecret',
    symbol: 'FATS',
    decimals: 3,
    icon: 'https://assets.leapwallet.io/secret-tokens/fat_secret.png',
  },
  secret1tqltnm8f53xnprmnlurczf6sr86a4mgztafxzp: {
    name: 'Secret Maker',
    symbol: 'sMKR',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/mkr_ethereum.svg',
  },
  secret15c5ftq4rq7xq3tml4nphv2fvz3u7kg73a583qp: {
    name: 'Secret Synthetix Network',
    symbol: 'sSNX',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/snx_ethereum.svg',
  },
  secret15l9cqgz5uezgydrglaak5ahfac69kmx2qpd6xt: {
    name: 'Secret Finance',
    symbol: 'SEFI',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/sefi.svg',
  },
  secret16efkcwgj3vkxsfvk4j6zjz05ukfxg35zsrj0vs: {
    name: 'Enjin',
    symbol: 'sENJ',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/enj_ethereum.svg',
  },
  secret1s4fllut0e6vw0k3fxsg4fs6fm2ad6hn09zwgwv: {
    name: 'Secret REN',
    symbol: 'sREN',
    decimals: 18,
    icon: '',
  },
  secret1p4zvqgxggrrk435nj94p6la2g4xd0rwssgzpsr: {
    name: 'Secret BandToken',
    symbol: 'sBAND',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/band_ethereum.svg',
  },
  secret1yxwnyk8htvvq25x2z87yj0r5tqpev452fk6h5h: {
    name: 'Secret Aave Token',
    symbol: 'sAAVE',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/aave_ethereum.svg',
  },
  secret19g8edr6pa2s7ywuc3wys9sgk76kj2th7xtksey: {
    name: 'Tornado Cash',
    symbol: 'sTORN',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/torn_ethereum.svg',
  },
  secret1h0tn05w9cjtsz9stccq2xl5rha2fxl0n2d765t: {
    name: 'Secret AlphaToken',
    symbol: 'sALPHA',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/salpha.svg',
  },
  secret1nq7resltu9870ar7vdu2suhzplx84800jfj2ja: {
    name: 'Secret Basic Attention Token',
    symbol: 'sBAT',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/bat_ethereum.svg',
  },
  secret1ezg8weaamcr99848qhkqcf2ap5xz7nwe3cy22x: {
    name: 'Secret Basis Cash',
    symbol: 'sBAC',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/bac_ethereum.svg',
  },
  secret1d673zrls7z5sd7nzqavqs4uzahnzqxq9zk7e62: {
    name: 'Secret UNI WSCRT-ETH',
    symbol: 'sUNILP-WSCRT-ETH',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/unilp_ethereum.svg',
  },
  secret1wp8aj7tja30cek5wf5jwcv0xalw8vmdasfv2lh: {
    name: 'Secret Enjin Coin',
    symbol: 'sENJ',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/enj_ethereum.svg',
  },
  secret1el5uj9ns9sty682dem033pt50xsv5mklmsvy24: {
    name: 'THORChain (ERC20)',
    symbol: 'sRUNE',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/rune_ethereum.svg',
  },
  secret1rs389ss2jch4xjmxv5guru86s8y839nmjsrm5d: {
    name: 'Secret KyberNetwork',
    symbol: 'sKNC',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/knc_ethereum.svg',
  },
  secret1rgm2m5t530tdzyd99775n6vzumxa5luxcllml4: {
    name: 'Sienna',
    symbol: 'SIENNA',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/sienna.svg',
  },
  secret178t2cp33hrtlthphmt9lpd25qet349mg4kcega: {
    name: 'Secret Decentraland',
    symbol: 'sMANA',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/mana_ethereum.svg',
  },
  secret120vtzu6xjprp6pq0r8wprf3jlp86xr8uu0nlc5: {
    name: 'Secret ZRX',
    symbol: 'sZRX',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/zrx_ethereum.svg',
  },
  secret1szqzgpl9w42kekla57609y6dq2r39nf0ncx400: {
    name: 'Secret Compound',
    symbol: 'sCOMP',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/comp_ethereum.svg',
  },
  secret1tact8rxxrvynk4pwukydnle4l0pdmj0sq9j9d5: {
    name: 'Secret BNB Token',
    symbol: 'sBNB(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/bnb_binance.svg',
  },
  secret1px5mtmjh072znpez4fjpmxqsv3hpevdpyu9l4v: {
    name: 'Secret Binance-Peg Polkadot',
    symbol: 'sDOT(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/dot_binance.svg',
  },
  secret1m6a72200733a7jnm76xrznh9cpmt4kf5ql0a6t: {
    name: 'Binance-peg Ethereum',
    symbol: 'sETH(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/eth_binance.svg',
  },
  secret1t6228qgqgkwhnsegk84ahljgw2cj7f9xprk9zd: {
    name: 'Secret Binance-peg Cardano',
    symbol: 'sADA(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/ada_binance.svg',
  },
  secret16nqax7x66z4efpu3y0kssdfnhg93va0h20yjre: {
    name: 'Secret Binance-pegged Dogecoin',
    symbol: 'sDOGE(BSC)',
    decimals: 8,
    icon: 'https://assets.leapwallet.io/secret-tokens/doge_binance.svg',
  },
  secret16euwqyntvsp0fp2rstmggw77w5xgz2z26cpwxj: {
    name: 'Secret Binance-peg USDT',
    symbol: 'sUSDT(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/usdt_binance.svg',
  },
  secret1kf45vm4mg5004pgajuplcmkrzvsyp2qtvlklyg: {
    name: 'Binance-pegged USDC',
    symbol: 'sUSDC(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/usdc_binance.svg',
  },
  secret1793ctg56epnzjlv7t7mug2tv3s2zylhqssyjwe: {
    name: 'Binance-peg BUSD',
    symbol: 'sBUSD(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/busd_binance.svg',
  },
  secret17w6pnfv0yn9k99dc8wttz5h0e0e6hz5pt8k2yu: {
    name: 'Staking Derivative Token',
    symbol: 'dSCRT',
    decimals: 6,
    icon: '',
  },
  secret1trr50jqff3ncn099cpukehh8a4pjxu0d3m4ccq: {
    name: 'Binance-peg ChainLink',
    symbol: 'sLINK(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/link_binance.svg',
  },
  secret1jk0tw00vs23n8jwqdzrxtln6ww2a3k6em7s0p2: {
    name: 'Secret YF Link',
    symbol: 'sYFL',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/yfl_ethereum.svg',
  },
  secret1npxd6pyh7ujhdsk7cvmq93y2v5uccj79sccch5: {
    name: 'Secret Venus',
    symbol: 'sXVS',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/xvs_binance.svg',
  },
  secret19ungtd2c7srftqdwgq0dspwvrw63dhu79qxv88: {
    name: 'Secret Monero',
    symbol: 'sXMR',
    decimals: 12,
    icon: 'https://assets.leapwallet.io/secret-tokens/sXMR.png',
  },
  secret1yxcexylwyxlq58umhgsjgstgcg2a0ytfy4d9lt: {
    name: 'Buttcoin',
    symbol: 'BUTT',
    decimals: 6,
    icon: '',
  },
  secret1gjay0a6m3wa92hm464p7t9v64q74azgxkz7at3: {
    name: 'LerdCoin',
    symbol: 'LERD',
    decimals: 18,
    icon: '',
  },
  secret1j0urq4pfrjr55c95z9s9jzv0evj88gjc9m0h02: {
    name: 'Binance-peg XRP',
    symbol: 'sXRP(BSC)',
    decimals: 18,
    icon: 'https://assets.leapwallet.io/secret-tokens/xrp_binance.svg',
  },
  secret129h4vu66y3gry6wzwa24rw0vtqjyn8tujuwtn9: {
    name: 'Secret UST',
    symbol: 'sUST',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/ust.png',
  },
  secret1ra7avvjh9fhr7dtr3djutugwj59ptctsrakyyw: {
    name: 'Secret Luna',
    symbol: 'sLUNA',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/luna.png',
    snip24Enabled: true,
  },
  secret1c7apt5mmv9ma5dpa9tmwjunhhke9de2206ufyp: {
    name: 'Binance-peg SCRT',
    symbol: 'sSCRT(BSC)',
    decimals: 6,
    icon: '',
  },
  secret1mua5u2aq26htqttexlvdcehajyl3zs0xa3zamr: {
    name: 'Lunar Coin',
    symbol: 'XDM',
    decimals: 8,
    icon: '',
  },
  secret1k8cge73c3nh32d4u0dsd5dgtmk63shtlrfscj5: {
    name: 'Secret DVPN',
    symbol: 'sDVPN',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/dvpn.png',
  },
  secret12rcvz0umvk875kd6a803txhtlu7y0pnd73kcej: {
    name: 'ALTER',
    symbol: 'ALTER',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/alter.svg',
  },
  secret1qfql357amn448duf5gvp9gr48sxx9tsnhupu3d: {
    name: 'Shade',
    symbol: 'SHD',
    decimals: 8,
    icon: 'https://assets.leapwallet.io/secret-tokens/shade.svg',
  },
  secret1ntvxnf5hzhzv8g87wn76ch6yswdujqlgmjh32w: {
    name: 'Secret HUAHUA',
    symbol: 'sHUAHUA',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/huahua.png',
    coingeckoId: 'hua',
    snip24Enabled: true,
  },
  secret1k6u0cy4feepm6pehnz804zmwakuwdapm69tuc4: {
    name: 'Staked SCRT Derivative (Shade)',
    symbol: 'stkd-SCRT',
    decimals: 6,
    icon: '',
  },
  secret16zfat8th6hvzhesj8f6rz3vzd7ll69ys580p2t: {
    name: 'SCRT Staking Derivative Token',
    symbol: 'seScrt',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/sescrt.png',
  },
  secret1xf6ljly737wq429ejl3jqrzvdu4j6zy87nvu4a: {
    name: 'Staking Derivative Token',
    symbol: 'dSCRT',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/sescrt.png',
  },
  secret1vw49sycxzzsyjwtzazys5h4wjpz65wxm4qxj20: {
    name: 'Staking Derivative Token',
    symbol: 'dSCRT',
    decimals: 6,
    icon: 'https://assets.leapwallet.io/secret-tokens/selenian.svg',
  },
};
