import { CosmosBlockchain } from '../connectors';

export const TX_LOG_COSMOS_BLOCKCHAIN_MAP = {
  akash: CosmosBlockchain.Akash,
  assetmantle: CosmosBlockchain.AssetMantle,
  axelar: CosmosBlockchain.Axelar,
  comdex: CosmosBlockchain.Comdex,
  crescent: CosmosBlockchain.Cresent,
  cryptoorg: CosmosBlockchain.CryptoOrgChain,
  emoney: CosmosBlockchain.EMoney,
  irisnet: CosmosBlockchain.IrisNet,
  juno: CosmosBlockchain.Juno,
  osmosis: CosmosBlockchain.Osmosis,
  persistenceNew: CosmosBlockchain.Persistence,
  persistence: CosmosBlockchain.Persistence,
  secret: CosmosBlockchain.Secret,
  secretnetwork: CosmosBlockchain.Secret,
  sifchain: CosmosBlockchain.Sifchain,
  sommelier: CosmosBlockchain.Sommelier,
  stargaze: CosmosBlockchain.Stargaze,
  starname: CosmosBlockchain.Starname,
  umee: CosmosBlockchain.Umee,
  cosmos: CosmosBlockchain.CosmosHub,
  injective: CosmosBlockchain.Injective,
  kujira: CosmosBlockchain.Kujira,
  sei: CosmosBlockchain.Sei,
  stride: CosmosBlockchain.Stride,
  agoric: CosmosBlockchain.Agoric,
  cheqd: CosmosBlockchain.Cheqd,
  likecoin: CosmosBlockchain.LikeCoin,
  gravitybridge: CosmosBlockchain.GravityBridge,
  chihuahua: CosmosBlockchain.Chihuahua,
  fetchhub: CosmosBlockchain.FetchHub,
  teritori: CosmosBlockchain.Teritori,
  desmos: CosmosBlockchain.Desmos,
  jackal: CosmosBlockchain.Jackal,
  bitsong: CosmosBlockchain.BitSong,
  evmos: CosmosBlockchain.Evmos,
  bitcanna: CosmosBlockchain.Bitcanna,
  canto: CosmosBlockchain.Canto,
  decentr: CosmosBlockchain.Decentr,
  carbon: CosmosBlockchain.Carbon,
  kava: CosmosBlockchain.Kava,
  omniflix: CosmosBlockchain.OmniFlix,
  passage: CosmosBlockchain.Passage,
  terra: CosmosBlockchain.Terra,
  quasar: CosmosBlockchain.Quasar,
  neutron: CosmosBlockchain.Neutron,
  coreum: CosmosBlockchain.Coreum,
  mainCoreum: CosmosBlockchain.Coreum,
  quicksilver: CosmosBlockchain.QuickSilver,
  onomy: CosmosBlockchain.Onomy,
  seiTestnet2: CosmosBlockchain.Sei,
  migaloo: CosmosBlockchain.Migaloo,
  kyve: CosmosBlockchain.Kyve,
  archway: CosmosBlockchain.Archway,
  noble: CosmosBlockchain.Noble,
  impacthub: CosmosBlockchain.Ixo,
  planq: CosmosBlockchain.Planq,
  nomic: CosmosBlockchain.Nomic,
  nibiru: CosmosBlockchain.Nibiru,
  mayachain: CosmosBlockchain.mayaChain,
  empowerchain: CosmosBlockchain.EmpowerChain,
  provenance: CosmosBlockchain.Provenance,
  kichain: CosmosBlockchain.Ki,
  sentinel: CosmosBlockchain.Sentinel,
  bandchain: CosmosBlockchain.Band,
  dydx: 'DYDX' as CosmosBlockchain,
  sge: 'SGE' as CosmosBlockchain,
  celestia: 'CELESTIA' as CosmosBlockchain,
  gitopia: CosmosBlockchain.Gitopia,
  xpla: 'XPLA' as CosmosBlockchain,
  aura: 'AURA' as CosmosBlockchain,
  chain4energy: CosmosBlockchain.chain4Energy,
  composable: 'COMPOSABLE' as CosmosBlockchain,
  nolus: CosmosBlockchain.Nolus,
  dymension: 'DYMENSION' as CosmosBlockchain,
  pryzmtestnet: 'PRYZM' as CosmosBlockchain,
  thorchain: 'THOR_CHAIN' as CosmosBlockchain,
  odin: 'ODIN_CHAIN' as CosmosBlockchain,
  ['8ball']: 'EIGHT_BALL' as CosmosBlockchain,
  ['Dora Vota']: 'DORAVOTA' as CosmosBlockchain,
  ['f(x)Core']: 'FX_CORE' as CosmosBlockchain,
  humans: 'HUMANS_AI' as CosmosBlockchain,
  ['union Testnet']: 'UNION' as CosmosBlockchain,
  ['Cronos POS Chain']: 'CRYPTO_ORG_CHAIN' as CosmosBlockchain,
  ['Haqq Network']: 'HAQQ_NETWORK' as CosmosBlockchain,
  ['Elys Network']: 'ELYS_NETWORK' as CosmosBlockchain,
  ['MANTRA Hongbai Testnet']: 'MANTRA_HONGBAI' as CosmosBlockchain,
  ['Scorum Network']: 'SCORUM_NETWORK' as CosmosBlockchain,
  saga: 'SAGA' as CosmosBlockchain,
  initia: 'INITIA' as CosmosBlockchain,
  titan: 'TITAN' as CosmosBlockchain,
  doravota: 'DORAVOTA' as CosmosBlockchain,
  fxcore: 'FX_CORE' as CosmosBlockchain,
  uniontestnet: 'UNION' as CosmosBlockchain,
  cronos: 'CRYPTO_ORG_CHAIN' as CosmosBlockchain,
  haqq: 'HAQQ_NETWORK' as CosmosBlockchain,
  elystestnet: 'ELYS_NETWORK' as CosmosBlockchain,
  mantrachaintestnet: 'MANTRA_HONGBAI' as CosmosBlockchain,
  scorum: 'SCORUM_NETWORK' as CosmosBlockchain,
};
